version: "3.8"

services:
  parser:
    build: .
    restart: always
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost/ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
